complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 40
  LongMethod:
    allowedLines: 120
  TooManyFunctions:
    allowedFunctionsPerFile: 20
    allowedFunctionsPerClass: 20

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
