on:
  push:
    tags:
      - 'mcp-server/v*'

jobs:
  deploy:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_deploy-module.yml
    with:
      module: mcp-server
      environment: production-mcp-server
    secrets: inherit
